### ISSUE TITLE
Unsuccessful version detection doesn't error

### ISSUE THREAD

**Issue by GeeTransit** [ofek/hatch-vcs#1]
The README says that if `fallback-version` isn't specified, "unsuccessful version detection will raise an error." However, running `hatch version` outside a Git repository (but still with a pyproject.toml) prints an empty line instead of erroring.

This doesn't impact me currently but it might cause some confusion when installing from a Git archive because it'll complain about the empty version (`packaging.version.InvalidVersion: Invalid version: ''`) instead of the version not existing.

(Seems like [this line](https://github.com/ofek/hatch-vcs/blob/8f772349fac8323db2564939305d3909d9ee9d8b/hatch_vcs/version_source.py#L31) is the cause.)

**Comment by ofek** [comment]
Thanks, fixed! https://github.com/ofek/hatch-vcs/releases/tag/v0.2.0

**Comment by dries007** [comment]
Sorry for necrobumpring, but I'm having the same issue, and even when I force the use of 0.2.0.
