### ISSUE TITLE
Note how to write version file without building

### ISSUE THREAD

**Issue by effigies** [ofek/hatch-vcs#27]
Coming from setuptools, it took me a bit to figure out that I should run `hatch build --hooks-only` to do the equivalent of `python -m setuptools_scm` and  write the version file into the source tree.

It might be useful to have in the README, for others who are trying to make sure their current workflow has equivalents in hatch before committing enough to dive deeply into the main hatch docs.

Or you can just close the issue, since hopefully I've put enough keywords in here that people can find it without any more work on your part. :-)

**Comment by ofek** [comment]
Hello! Would you mind opening a PR?

**Comment by effigies** [comment]
Sure thing: #28.

**Comment by lwasser** [comment]
thanks for this! i'm migrating from setuptools_scm too!
