### ISSUE TITLE
version-file under [tool.hatch.version] doesn't work

### ISSUE THREAD

**Issue by raamana** [ofek/hatch-vcs#37]
docs seems to suggest version-file must be under `[tool.hatch.version]` but it doesn't work. it needs to be under `[tool.hatch.build.hooks.vcs]`. it would help newbies to clarify this.

**Comment by ofek** [comment]
where do you see that? I'm looking at https://github.com/ofek/hatch-vcs#build-hook

**Comment by RonnyPfannschmidt** [comment]
@raamana is there perhaps a confusion between the builtin support for reading the version from a file and this plugin, which may write it

**Comment by raamana** [comment]
Sorry guys, I think I may have conflated a few different things, as this is all new to me. Anyways I think it would be easier for [total] newbies to write out a simple HOWTO guide to move from `versioneer` to `hatch-vcs`. Maybe I will write a simple one soon based on my experience.
