### ISSUE TITLE
Support building outside a VCS tree

### ISSUE THREAD

**Issue by stefanor** [ofek/hatch-vcs#4]
It's common to work with a Python source package outside of its upstream VCS tree, in a larger build system, e.g. a monorepo or a Linux Distribution.

In Debian, for example, while we maintain (most) of our packages in git, the archive's source package format is still a tarball. The git tree is not accessible at build time. And when inside the Debian source package git tree, the tag format is likely to be `upstream/1.2.3` or `debian/1.2.3-1`, not whatever the upstream's tag format is. Both of these mean tools like hatch-scm fail to detect the correct version, at bulid time.

In `setuptools_scm`, there work-around is [an environment variable `SETUPTOOLS_SCM_PRETEND_VERSION`](https://github.com/pypa/setuptools_scm#environment-variables). When this is set, it is used as the version, bypassing any attempt to determine the version from VCS, directly. Debian's build tools can set this environment variable, making it trivial to build `setuptools_scm` packages in Debian.

Can we support something similar in hatch-vcs?

**Comment by ofek** [comment]
That env var should Just Work ™️ , no?

**Comment by stefanor** [comment]
Doh, I hadn't even got as far as looking at the implementation, I thought we'd have to jump these hurdles first.

I'll file a PR to document this.

**Comment by helderco** [comment]
How does it work in a monorepo though? Let's say my `pyproject.toml` is in a subdir, does `hatch-vcs` support this?

And by the way @stefanor, if you don't get the version from vcs what does `hatch-vcs` do for you?

Thanks!
