### ISSUE TITLE
What is the metadata hook for?

### ISSUE THREAD

**Issue by flying-sheep** [ofek/hatch-vcs#45]
Does anything happen when you specify `[tool.hatch.metadata.hooks.vcs]` in addition to `[tool.hatch.version] source = "vcs"`?

When I leave out the metadata hook header, the built package’s metadata still contains a `setuptools-scm` generated version.

**Comment by RonnyPfannschmidt** [comment]
The metadata hook is for dynamically rendering scm data into projects metadata other than the version

**Comment by flying-sheep** [comment]
Ah, got it! The examples kinda hint toward that, but it’s not outright stated. Maybe that should be added.
