### ISSUE TITLE
`hatch-vcs` picks up an old version

### ISSUE THREAD

**Issue by Saransh-cpp** [ofek/hatch-vcs#47]
Thanks for creating this amazing library!

Recently, we accidentally created a [`liionpack`](https://github.com/pybamm-team/liionpack) release with the tag [`v.0.3.4`](https://github.com/pybamm-team/liionpack/tags) (which is not compatible with `hatch-vcs`). The tag was recently renamed to `v0.3.4`, creating some confusion for `git` (see how [releases](https://github.com/pybamm-team/liionpack/releases) and [tags](https://github.com/pybamm-team/liionpack/tags) are not in sequence, but still, the latest tag is `v0.3.7`). 

https://github.com/pybamm-team/liionpack/pull/270 aims to migrate to `hatch-vcs`, but for some reason, `hatch-vcs` keeps on picking up the version `v0.3.5` while installing `liionpack`, whereas, the latest version is `v0.3.7`. 

Could you please let us know where we are going wrong? Thanks!

**Comment by RonnyPfannschmidt** [comment]
I believe this issue needs to transfer to setuptools-scm

**Comment by Saransh-cpp** [comment]
Oh yes, that makes sense. I'll shift this.
