### ISSUE TITLE
'UserWarning: template='' looks like a error, using default instead' for setuptools-scm v8.0.0+

### ISSUE THREAD

**Issue by matthewfeickert** [ofek/hatch-vcs#49]
Hi. Just reporting this low importance warning as we caught it in https://github.com/scikit-hep/pyhf/pull/2337 and I don't have the time to open a PR right now today. For `setuptools-scm` `v8.0.0+` in

https://github.com/ofek/hatch-vcs/blob/425d529cd24295311ca5b52b589a6308165fb244/hatch_vcs/build_hook.py#L40-L43

using `''` to handle the `None` case

https://github.com/ofek/hatch-vcs/blob/425d529cd24295311ca5b52b589a6308165fb244/hatch_vcs/build_hook.py#L30-L32

results in `setuptools-scm` raising a `UserWarning`

```
UserWarning: template='' looks like a error, using default instead
```

While very minor, I tought it might still be good to reduce raised warnings.

**Comment by ofek** [comment]
Thanks!

**Comment by matthewfeickert** [comment]
Thanks @effigies and @ofek.

@ofek not to poke, or presume any schedules you have on this, but it would be great if there could be a new release with PR #55 included in it. I would normally ask for a patch release, but as there's been a change in lower bound for `requires-python` in PR #56 between [`v0.3.0`](https://github.com/ofek/hatch-vcs/releases/tag/v0.3.0) and now

https://github.com/ofek/hatch-vcs/compare/v0.3.0...029f2a1b07c13722645007d9f3f7d0a98ecaac99

could a `v0.4.0` be released?

**Comment by ofek** [comment]
Yes indeed! I was just about to actually: https://github.com/ofek/hatch-vcs/pull/57#pullrequestreview-1714018132

Give me just another hour or so, I'm almost finished what I'm working on

**Comment by ofek** [comment]
https://github.com/ofek/hatch-vcs/releases/tag/v0.4.0

**Comment by matthewfeickert** [comment]
Fantastic! Thanks so much @ofek.
