### ISSUE TITLE
setuptools-scm warning raised when `tag-pattern` is not defined

### ISSUE THREAD

**Issue by edgarrmondragon** [ofek/hatch-vcs#67]
This package defaults to an empty string when `tag-pattern` is not defined by the user:

https://github.com/ofek/hatch-vcs/blob/e186a8b5d97dd9c9f93ae6015139b55411d9011b/hatch_vcs/version_source.py#L17-L26

This is causing `setuptools-scm` to raise a deprecation warning:

```
DeprecationWarning: Error getting the version from source `vcs`: empty regex for tag regex is invalid, using default
```

This warning is coming from https://github.com/pypa/setuptools_scm/blob/102f56a896bc4ea8d4c58d9c49f455f15310de38/src/setuptools_scm/_get_version_impl.py#L167-L175.

I don't know what the best solution is (if one's really needed) other than repeating setuptools_scm's default string value in this codebase.

**Comment by ofek** [comment]
Could we import the default value? I'm definitely open to PRs!

**Comment by mihaic** [comment]
The PyPI version does not include with the fix for this issue. Could we please have a new release?
